pruebas_index:
  path: /pruebas/{lang}/{name}/{surname}/{page}
  defaults: {_controller: AppBundle:Pruebas:index, lang: es, surname: contenido vacio}
  methods: [GET, POST]
  requirements:
      name: \w+
      page: \d+
      lang: es|en|fr

pruebas_create:
  path: /pruebas/create
  defaults: { _controller: AppBundle:Pruebas:create }      