AppBundle\Entity\Curso:
    properties:
        titulo:
            - NotBlank: {message: "El titulo no puede estar vacío!"}
            - Length:
                min: 5
                minMessage: "El titulo debe tener mas de cinco caracteres!"
        descripcion:
            - NotBlank: {message: "La descripción no puede estar vacia!"}
        precio:
            - Type:
                type: numeric
                message: "El precio tiene que ser numerico!"  