parameters:
    my_mailer.class:     AppBundle\Services\Mailer
   my_mailer.transport: sendmail
services:
    app.admin.post:
        class: AppBundle\Admin\PostAdmin
        arguments: [~, AppBundle\Entity\Post, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Post }
        public: true
my_mailer:
    class:       "%my_mailer.class%"
       arguments:   ["%my_mailer.transport%"]